// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMKYwh13VWE1SghY6zSa7ohqCohJSckGg',
    appId: '1:180540721054:web:7a47edb2b18a3cb168788f',
    messagingSenderId: '180540721054',
    projectId: 'mailflow-457112',
    authDomain: 'mailflow-457112.firebaseapp.com',
    storageBucket: 'mailflow-457112.firebasestorage.app',
    measurementId: 'G-ZBL08H868G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVbxLrhpCcQuyehU6WQgFggwmw_JgeAMM',
    appId: '1:180540721054:android:5607803a05cd1af968788f',
    messagingSenderId: '180540721054',
    projectId: 'mailflow-457112',
    storageBucket: 'mailflow-457112.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0FZHUIhg6ksTChqgu7QSFYGfTTItNefA',
    appId: '1:180540721054:ios:1cce5ed136dc616768788f',
    messagingSenderId: '180540721054',
    projectId: 'mailflow-457112',
    storageBucket: 'mailflow-457112.firebasestorage.app',
    androidClientId: '180540721054-pe2cv50k1ue3cfns0b72l374r9r4mrtr.apps.googleusercontent.com',
    iosBundleId: 'com.example.mailMerge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0FZHUIhg6ksTChqgu7QSFYGfTTItNefA',
    appId: '1:180540721054:ios:1cce5ed136dc616768788f',
    messagingSenderId: '180540721054',
    projectId: 'mailflow-457112',
    storageBucket: 'mailflow-457112.firebasestorage.app',
    androidClientId: '180540721054-pe2cv50k1ue3cfns0b72l374r9r4mrtr.apps.googleusercontent.com',
    iosBundleId: 'com.example.mailMerge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMKYwh13VWE1SghY6zSa7ohqCohJSckGg',
    appId: '1:180540721054:web:433c5844d429602668788f',
    messagingSenderId: '180540721054',
    projectId: 'mailflow-457112',
    authDomain: 'mailflow-457112.firebaseapp.com',
    storageBucket: 'mailflow-457112.firebasestorage.app',
    measurementId: 'G-ZXZ39Y43ZC',
  );
}
